# Generated by Django 2.2.2 on 2019-10-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webpage_name', models.CharField(max_length=264, unique=True)),
                ('url_name', models.URLField(unique=True)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MODEL_CREATION.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_accessed', models.DateField()),
                ('webpage_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MODEL_CREATION.WebPage')),
            ],
        ),
    ]
